In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

/var/folders/86/34g0tdgx7kvf_73pr3h67_700000gn/T/ipykernel_59922/3828565490.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desrip,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

In [6]:
# books["tagged_description"].to_csv("tagged_description.txt",
#                                    sep = "\n",
#                                    index = False,
#                                    header = False)
books["tagged_description"].to_csv("tagged_description.txt", index=False, header=False)

In [7]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 100
Created a chunk of size 1216, which is longer than the specified 100
Created a chunk of size 375, which is longer than the specified 100
Created a chunk of size 311, which is longer than the specified 100
Created a chunk of size 483, which is longer than the specified 100
Created a chunk of size 484, which is longer than the specified 100
Created a chunk of size 962, which is longer than the specified 100
Created a chunk of size 188, which is longer than the specified 100
Created a chunk of size 845, which is longer than the specified 100
Created a chunk of size 296, which is longer than the specified 100
Created a chunk of size 197, which is longer than the specified 100
Created a chunk of size 881, which is longer than the specified 100
Created a chunk of size 1090, which is longer than the specified 100
Created a chunk of size 1191, which is longer than the specified 100
Created a chunk of size 306, which is longer than the specified 100
Created a chunk of size 270, which is longer than the specified 100
Created a chunk of size 213, which is longer than the specified 100
Created a chunk of size 216, which is longer than the specified 100
Created a chunk of size 515, which is longer than the specified 100
Created a chunk of size 754, which is longer than the specified 100
Created a chunk of size 390, which is longer than the specified 100
Created a chunk of size 265, which is longer than the specified 100
Created a chunk of size 253, which is longer than the specified 100
Created a chunk of size 308, which is longer than the specified 100
Created a chunk of size 730, which is longer than the specified 100
Created a chunk of size 723, which is longer than the specified 100
Created a chunk of size 258, which is longer than the specified 100
Created a chunk of size 475, which is longer than the specified 100
Created a chunk of size 272, which is longer than the specified 100
Created a chunk of size 1267, which is longer than the specified 100
Created a chunk of size 683, which is longer than the specified 100
Created a chunk of size 243, which is longer than the specified 100
Created a chunk of size 555, which is longer than the specified 100
Created a chunk of size 523, which is longer than the specified 100
Created a chunk of size 282, which is longer than the specified 100
Created a chunk of size 789, which is longer than the specified 100
Created a chunk of size 566, which is longer than the specified 100
Created a chunk of size 525, which is longer than the specified 100
Created a chunk of size 179, which is longer than the specified 100
Created a chunk of size 299, which is longer than the specified 100
Created a chunk of size 535, which is longer than the specified 100
Created a chunk of size 559, which is longer than the specified 100
Created a chunk of size 565, which is longer than the specified 100
Created a chunk of size 385, which is longer than the specified 100
Created a chunk of size 412, which is longer than the specified 100
Created a chunk of size 463, which is longer than the specified 100
Created a chunk of size 597, which is longer than the specified 100
Created a chunk of size 478, which is longer than the specified 100
Created a chunk of size 461, which is longer than the specified 100
Created a chunk of size 259, which is longer than the specified 100
Created a chunk of size 306, which is longer than the specified 100
Created a chunk of size 616, which is longer than the specified 100
Created a chunk of size 421, which is longer than the specified 100
Created a chunk of size 889, which is longer than the specified 100
Created a chunk of size 695, which is longer than the specified 100
Created a chunk of size 304, which is longer than the specified 100
Created a chunk of size 219, which is longer than the specified 100
Created a chunk of size 277, which is longer than the specified 100
Created a chunk of size 2010, which is longer than the specified 100
Created a chunk of size 175, which is longer than the specified 100
Created a chunk of size 481, which is longer than the specified 100
Created a chunk of size 302, which is longer than the specified 100
Created a chunk of size 522, which is longer than the specified 100
Created a chunk of size 649, which is longer than the specified 100
Created a chunk of size 778, which is longer than the specified 100
Created a chunk of size 165, which is longer than the specified 100
Created a chunk of size 688, which is longer than the specified 100
Created a chunk of size 550, which is longer than the specified 100
Created a chunk of size 1225, which is longer than the specified 100
Created a chunk of size 408, which is longer than the specified 100
Created a chunk of size 1186, which is longer than the specified 100
Created a chunk of size 1216, which is longer than the specified 100
Created a chunk of size 1193, which is longer than the specified 100
Created a chunk of size 1059, which is longer than the specified 100
Created a chunk of size 246, which is longer than the specified 100
Created a chunk of size 690, which is longer than the specified 100
Created a chunk of size 878, which is longer than the specified 100
Created a chunk of size 286, which is longer than the specified 100
Created a chunk of size 768, which is longer than the specified 100
Created a chunk of size 389, which is longer than the specified 100
Created a chunk of size 419, which is longer than the specified 100
Created a chunk of size 210, which is longer than the specified 100
Created a chunk of size 209, which is longer than the specified 100
Created a chunk of size 725, which is longer than the specified 100
Created a chunk of size 209, which is longer than the specified 100
Created a chunk of size 163, which is longer than the specified 100
Created a chunk of size 528, which is longer than the specified 100
Created a chunk of size 523, which is longer than the specified 100
Created a chunk of size 214, which is longer than the specified 100
Created a chunk of size 340, which is longer than the specified 100
Created a chunk of size 901, which is longer than the specified 100
Created a chunk of size 1272, which is longer than the specified 100
Created a chunk of size 560, which is longer than the specified 100
Created a chunk of size 1637, which is longer than the specified 100
Created a chunk of size 438, which is longer than the specified 100
Created a chunk of size 251, which is longer than the specified 100
Created a chunk of size 779, which is longer than the specified 100
Created a chunk of size 718, which is longer than the specified 100
Created a chunk of size 516, which is longer than the specified 100
Created a chunk of size 960, which is longer than the specified 100
Created a chunk of size 200, which is longer than the specified 100
Created a chunk of size 1132, which is longer than the specified 100
Created a chunk of size 170, which is longer than the specified 100
Created a chunk of size 1325, which is longer than the specified 100
Created a chunk of size 853, which is longer than the specified 100
Created a chunk of size 272, which is longer than the specified 100
Created a chunk of size 801, which is longer than the specified 100
Created a chunk of size 1121, which is longer than the specified 100
Created a chunk of size 838, which is longer than the specified 100
Created a chunk of size 262, which is longer than the specified 100
Created a chunk of size 237, which is longer than the specified 100
Created a chunk of size 734, which is longer than the specified 100
Created a chunk of size 1195, which is longer than the specified 100
Created a chunk of size 712, which is longer than the specified 100
Created a chunk of size 775, which is longer than the specified 100
Created a chunk of size 280, which is longer than the specified 100
Created a chunk of size 309, which is longer than the specified 100
Created a chunk of size 358, which is longer than the specified 100
Created a chunk of size 768, which is longer than the specified 100
Created a chunk of size 767, which is longer than the specified 100
Created a chunk of size 718, which is longer than the specified 100
Created a chunk of size 2012, which is longer than the specified 100
Created a chunk of size 308, which is longer than the specified 100
Created a chunk of size 1288, which is longer than the specified 100
Created a chunk of size 1231, which is longer than the specified 100
Created a chunk of size 729, which is longer than the specified 100
Created a chunk of size 750, which is longer than the specified 100
Created a chunk of size 447, which is longer than the specified 100
Created a chunk of size 1242, which is longer than the specified 100
Created a chunk of size 311, which is longer than the specified 100
Created a chunk of size 914, which is longer than the specified 100
Created a chunk of size 306, which is longer than the specified 100
Created a chunk of size 846, which is longer than the specified 100
Created a chunk of size 1128, which is longer than the specified 100
Created a chunk of size 1075, which is longer than the specified 100
Created a chunk of size 1320, which is longer than the specified 100
Created a chunk of size 363, which is longer than the specified 100
Created a chunk of size 2834, which is longer than the specified 100
Created a chunk of size 237, which is longer than the specified 100
Created a chunk of size 242, which is longer than the specified 100
Created a chunk of size 173, which is longer than the specified 100
Created a chunk of size 206, which is longer than the specified 100
Created a chunk of size 572, which is longer than the specified 100
Created a chunk of size 208, which is longer than the specified 100
Created a chunk of size 367, which is longer than the specified 100
Created a chunk of size 1143, which is longer than the specified 100
Created a chunk of size 1006, which is longer than the specified 100
Created a chunk of size 715, which is longer than the specified 100
Created a chunk of size 712, which is longer than the specified 100
Created a chunk of size 2510, which is longer than the specified 100
Created a chunk of size 956, which is longer than the specified 100
Created a chunk of size 309, which is longer than the specified 100
Created a chunk of size 351, which is longer than the specified 100
Created a chunk of size 641, which is longer than the specified 100
Created a chunk of size 405, which is longer than the specified 100
Created a chunk of size 525, which is longer than the specified 100
Created a chunk of size 795, which is longer than the specified 100
Created a chunk of size 167, which is longer than the specified 100
Created a chunk of size 391, which is longer than the specified 100
Created a chunk of size 256, which is longer than the specified 100
Created a chunk of size 1424, which is longer than the specified 100
Created a chunk of size 1085, which is longer than the specified 100
Created a chunk of size 1146, which is longer than the specified 100
Created a chunk of size 1268, which is longer than the specified 100
Created a chunk of size 790, which is longer than the specified 100
Created a chunk of size 297, which is longer than the specified 100
Created a chunk of size 1088, which is longer than the specified 100
Created a chunk of size 874, which is longer than the specified 100
Created a chunk of size 256, which is longer than the specified 100
Created a chunk of size 876, which is longer than the specified 100
Created a chunk of size 808, which is longer than the specified 100
Created a chunk of size 1814, which is longer than the specified 100
Created a chunk of size 1830, which is longer than the specified 100
Created a chunk of size 1064, which is longer than the specified 100
Created a chunk of size 955, which is longer than the specified 100
Created a chunk of size 1182, which is longer than the specified 100
Created a chunk of size 283, which is longer than the specified 100
Created a chunk of size 283, which is longer than the specified 100
Created a chunk of size 288, which is longer than the specified 100
Created a chunk of size 1286, which is longer than the specified 100
Created a chunk of size 1644, which is longer than the specified 100
Created a chunk of size 759, which is longer than the specified 100
Created a chunk of size 1932, which is longer than the specified 100
Created a chunk of size 874, which is longer than the specified 100
Created a chunk of size 2008, which is longer than the specified 100
Created a chunk of size 2285, which is longer than the specified 100
Created a chunk of size 173, which is longer than the specified 100
Created a chunk of size 1003, which is longer than the specified 100
Created a chunk of size 579, which is longer than the specified 100
Created a chunk of size 290, which is longer than the specified 100
Created a chunk of size 255, which is longer than the specified 100
Created a chunk of size 1144, which is longer than the specified 100
Created a chunk of size 559, which is longer than the specified 100
Created a chunk of size 1143, which is longer than the specified 100
Created a chunk of size 245, which is longer than the specified 100
Created a chunk of size 1088, which is longer than the specified 100
Created a chunk of size 1483, which is longer than the specified 100
Created a chunk of size 223, which is longer than the specified 100
Created a chunk of size 1137, which is longer than the specified 100
Created a chunk of size 724, which is longer than the specified 100
Created a chunk of size 668, which is longer than the specified 100
Created a chunk of size 767, which is longer than the specified 100
Created a chunk of size 608, which is longer than the specified 100
Created a chunk of size 572, which is longer than the specified 100
Created a chunk of size 967, which is longer than the specified 100
Created a chunk of size 859, which is longer than the specified 100
Created a chunk of size 1034, which is longer than the specified 100
Created a chunk of size 191, which is longer than the specified 100
Created a chunk of size 367, which is longer than the specified 100
Created a chunk of size 497, which is longer than the specified 100
Created a chunk of size 652, which is longer than the specified 100
Created a chunk of size 350, which is longer than the specified 100
Created a chunk of size 735, which is longer than the specified 100
Created a chunk of size 527, which is longer than the specified 100
Created a chunk of size 1017, which is longer than the specified 100
Created a chunk of size 972, which is longer than the specified 100
Created a chunk of size 206, which is longer than the specified 100
Created a chunk of size 690, which is longer than the specified 100
Created a chunk of size 546, which is longer than the specified 100
Created a chunk of size 244, which is longer than the specified 100
Created a chunk of size 209, which is longer than the specified 100
Created a chunk of size 378, which is longer than the specified 100
Created a chunk of size 933, which is longer than the specified 100
Created a chunk of size 564, which is longer than the specified 100
Created a chunk of size 856, which is longer than the specified 100
Created a chunk of size 717, which is longer than the specified 100
Created a chunk of size 749, which is longer than the specified 100
Created a chunk of size 714, which is longer than the specified 100
Created a chunk of size 326, which is longer than the specified 100
Created a chunk of size 243, which is longer than the specified 100
Created a chunk of size 1090, which is longer than the specified 100
Created a chunk of size 725, which is longer than the specified 100
Created a chunk of size 247, which is longer than the specified 100
Created a chunk of size 229, which is longer than the specified 100
Created a chunk of size 706, which is longer than the specified 100
Created a chunk of size 1914, which is longer than the specified 100
Created a chunk of size 397, which is longer than the specified 100
Created a chunk of size 487, which is longer than the specified 100
Created a chunk of size 622, which is longer than the specified 100
Created a chunk of size 561, which is longer than the specified 100
Created a chunk of size 558, which is longer than the specified 100
Created a chunk of size 388, which is longer than the specified 100
Created a chunk of size 231, which is longer than the specified 100
Created a chunk of size 427, which is longer than the specified 100
Created a chunk of size 418, which is longer than the specified 100
Created a chunk of size 284, which is longer than the specified 100
Created a chunk of size 168, which is longer than the specified 100
Created a chunk of size 626, which is longer than the specified 100
Created a chunk of size 2616, which is longer than the specified 100
Created a chunk of size 1580, which is longer than the specified 100
Created a chunk of size 391, which is longer than the specified 100
Created a chunk of size 996, which is longer than the specified 100
Created a chunk of size 849, which is longer than the specified 100
Created a chunk of size 265, which is longer than the specified 100
Created a chunk of size 338, which is longer than the specified 100
Created a chunk of size 1530, which is longer than the specified 100
Created a chunk of size 215, which is longer than the specified 100
Created a chunk of size 291, which is longer than the specified 100
Created a chunk of size 2032, which is longer than the specified 100
Created a chunk of size 398, which is longer than the specified 100
Created a chunk of size 1619, which is longer than the specified 100
Created a chunk of size 700, which is longer than the specified 100
Created a chunk of size 824, which is longer than the specified 100
Created a chunk of size 356, which is longer than the specified 100
Created a chunk of size 843, which is longer than the specified 100
Created a chunk of size 1191, which is longer than the specified 100
Created a chunk of size 197, which is longer than the specified 100
Created a chunk of size 510, which is longer than the specified 100
Created a chunk of size 665, which is longer than the specified 100
Created a chunk of size 1284, which is longer than the specified 100
Created a chunk of size 262, which is longer than the specified 100
Created a chunk of size 244, which is longer than the specified 100
Created a chunk of size 217, which is longer than the specified 100
Created a chunk of size 200, which is longer than the specified 100
Created a chunk of size 1268, which is longer than the specified 100
Created a chunk of size 1277, which is longer than the specified 100
Created a chunk of size 200, which is longer than the specified 100
Created a chunk of size 1058, which is longer than the specified 100
Created a chunk of size 380, which is longer than the specified 100
Created a chunk of size 271, which is longer than the specified 100
Created a chunk of size 179, which is longer than the specified 100
Created a chunk of size 227, which is longer than the specified 100
Created a chunk of size 224, which is longer than the specified 100
Created a chunk of size 784, which is longer than the specified 100
Created a chunk of size 971, which is longer than the specified 100
Created a chunk of size 615, which is longer than the specified 100
Created a chunk of size 165, which is longer than the specified 100
Created a chunk of size 759, which is longer than the specified 100
Created a chunk of size 291, which is longer than the specified 100
Created a chunk of size 247, which is longer than the specified 100
Created a chunk of size 965, which is longer than the specified 100
Created a chunk of size 234, which is longer than the specified 100
Created a chunk of size 845, which is longer than the specified 100

In [8]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [9]:
from langchain_huggingface.embeddings import HuggingFaceEmbeddings

embedding = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

db_books = Chroma.from_documents(
    documents,
    embedding=embedding
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [10]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='6ea28db7-9c12-4b2b-bc0f-d7c720cc67ab', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='504c1764-19c2-45a0-aceb-6f16f6d1037b', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='995c60ca-7cce-4614-b649-b823beaaa002', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='082084fe-c6d7-44c0-831b-fb17847382f6', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(id='0434fd02-1394-4d98-89cb-2840273cfe16', metadata={'source': 'tagged_description.txt'}, page_content='"9780060959036 Barbara Kingsolver\'s fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel\'s intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."'),
 Document(id='01367a62-2da6-4700-885b-77fa09ac2d9a', metadata={'source': 'tagged_description.txt'}, page_content='"9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."'),
 Document(id='8d64ad52-4e01-4c89-ab7f-611c6d51f00b', metadata={'source': 'tagged_description.txt'}, page_content='"9780374522599 The Control of Nature is John McPhee\'s bestselling account of places where people are locked in combat with nature. Taking us deep into these contested territories, McPhee details the strageties and tactics through which people attempt to control nature. Most striking is his depiction of the main contestants: nature in complex and awesome guises, and those attempting to wrest control from her - stubborn, sometimes foolhardy, more often ingenious, and always arresting characters."'),
 Document(id='75a2d7ca-8b81-41d6-839e-d053d45ac117', metadata={'source': 'tagged_description.txt'}, page_content='"9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"'),
 Document(id='650a5a7c-5504-41d9-ba76-557111ef563a', metadata={'source': 'tagged_description.txt'}, page_content='"9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"'),
 Document(id='c3708e6d-54f7-48f9-bccf-80f49271a5a9', metadata={'source': 'tagged_description.txt'}, page_content='"9780802431486 Drawn from years of counseling and the author\'s own parenting experiences, this valuable resource, filled with Scripture passages and accompanying practical applications, provides principles for raising and nurturing children in these uncertain and rapidly changing times. Original."')]

In [14]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip('"').strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desrip,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [15]:

def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = [] #contain all isbn

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [16]:
#testing search results
retrieve_semantic_recommendations("A book about childhood trauma")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing_desrip,title_and_subtitle,tagged_description
159,9780060577865,006057786X,Bad Childhood---Good Life,Laura Schlessinger,Self-Help,http://books.google.com/books/content?id=2sepd...,"Exploring how the past influences the present,...",2006.0,3.92,272.0,502.0,0,Bad Childhood---Good Life: How to Blossom and ...,9780060577865 Exploring how the past influence...
282,9780060915186,0060915188,An American Childhood,Annie Dillard,Biography & Autobiography,http://books.google.com/books/content?id=tRihT...,A book that instantly captured the hearts of r...,1988.0,3.91,255.0,7086.0,0,An American Childhood,9780060915186 A book that instantly captured t...
334,9780060976118,006097611X,Operation Wandering Soul,Richard Powers,Fiction,http://books.google.com/books/content?id=nIGIm...,"Highly imaginative and emotionally powerful, t...",1994.0,3.62,352.0,366.0,0,Operation Wandering Soul,9780060976118 Highly imaginative and emotional...
337,9780060977498,0060977493,The God of Small Things,Arundhati Roy,Fiction,http://books.google.com/books/content?id=2GESv...,A debut novel of dark foreboding and family tr...,1998.0,3.93,321.0,6549.0,0,The God of Small Things,9780060977498 A debut novel of dark foreboding...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,0,Racso and the Rats of NIMH,"9780064402453 ‘Racso, a brash and boastful lit..."
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,0,The Rainbow People,"9780064404419 ""Culled from 69 stories collecte..."
412,9780064405713,0064405710,Crazy Lady!,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=aJwh7...,Increasingly alienated from his widowed father...,1995.0,3.64,192.0,1481.0,0,Crazy Lady!,9780064405713 Increasingly alienated from his ...
501,9780099456452,0099456451,The Spook's Apprentice,Joseph Delaney,Exorcism,http://books.google.com/books/content?id=ZA0yS...,A wonderful and terrifying series by a new wri...,2005.0,3.98,325.0,2733.0,0,The Spook's Apprentice,9780099456452 A wonderful and terrifying serie...
731,9780141015088,014101508X,How to Breathe Underwater,Julie Orringer,Families,http://books.google.com/books/content?id=t1v9V...,In her dazzling first book Julie Orringer dive...,2005.0,3.96,222.0,188.0,0,How to Breathe Underwater: Stories,9780141015088 In her dazzling first book Julie...
778,9780141311401,0141311401,Boy,Roald Dahl,"Authors, English",http://books.google.com/books/content?id=GmE-P...,'Throughout my young days at school and just a...,2001.0,4.10,176.0,42784.0,0,Boy: Tales of Childhood,9780141311401 'Throughout my young days at sch...
853,9780143037149,0143037145,The Memory Keeper's Daughter,Kim Edwards,Fiction,http://books.google.com/books/content?id=2yOky...,"In a tale spanning twenty-five years, a doctor...",2006.0,3.65,401.0,519878.0,0,The Memory Keeper's Daughter,9780143037149 In a tale spanning twenty-five y...
1220,9780312315733,0312315732,Little Children,Tom Perrotta,Fiction,http://books.google.com/books/content?id=j73yQ...,"A group of young suburban parents, including a...",2004.0,3.62,355.0,25811.0,0,Little Children: A Novel,9780312315733 A group of young suburban parent...
1254,9780312422738,0312422733,A Feather on the Breath of God,Sigrid Nunez,Fiction,http://books.google.com/books/content?id=Y9Kes...,Growing up in a New York housing project durin...,2005.0,3.87,192.0,447.0,0,A Feather on the Breath of God: A Novel,9780312422738 Growing up in a New York housing...
1348,9780316168816,0316168815,The Lovely Bones,Alice Sebold,Fiction,http://books.google.com/books/content?id=o-Qfn...,The spirit of fourteen-year-old Susie Salmon d...,2004.0,3.79,328.0,5776.0,0,The Lovely Bones,9780316168816 The spirit of fourteen-year-old ...
1389,9780330346511,0330346512,An Unquiet Mind,Kay Redfield Jamison,Biography & Autobiography,http://books.google.com/books/content?id=adEqu...,"In this book, a world authority on manic-depre...",1997.0,4.05,240.0,297.0,0,An Unquiet Mind: A Memoir of Moods and Madness,"9780330346511 In this book, a world authority ..."
1652,9780374528539,0374528535,"Get Out of My Life, But First Could You Drive ...",Anthony E. Wolf,Family & Relationships,http://books.google.com/books/content?id=oKdbC...,A lighthearted but insightful guide to raising...,2002.0,3.94,240.0,1301.0,0,"Get Out of My Life, But First Could You Drive ...",9780374528539 A lighthearted but insightful gu...
1675,9780375701474,0375701478,Night Falls Fast,Kay Redfield Jamison,NaN,http://books.google.com/books/content?id=NTeOD...,A study of the growing epidemic of suicide amo...,2011.0,4.09,432.0,5211.0,0,Night Falls Fast,9780375701474 A study of the growing epidemic ...
1867,9780385720106,0385720106,A Map of the World,Jane Hamilton,Fiction,http://books.google.com/books/content?id=HR8jz...,"While under the care of Alice Goodwin, a neigh...",1995.0,3.80,400.0,67012.0,0,A Map of the World,9780385720106 While under the care of Alice Go...
1880,9780385732550,0385732554,The Giver,Lois Lowry,Juvenile Fiction,http://books.google.com/books/content?id=oZRlY...,"At the age of twelve, Jonas, a young boy from ...",2006.0,4.12,208.0,1464909.0,0,The Giver,"9780385732550 At the age of twelve, Jonas, a y..."
1888,9780393040586,0393040585,The Confident Child,T. E. Apter,Family & Relationships,http://books.google.com/books/content?id=stxpQ...,"Focusing on children from age five to fifteen,...",1997.0,3.62,270.0,13.0,0,"The Confident Child: Raising a Child to Try, L...",9780393040586 Focusing on children from age fi...
1933,9780393703276,0393703274,The Body Remembers: The Psychophysiology of Tr...,Babette Rothschild,Health & Fitness,http://books.google.com/books/content?id=sq40y...,Relates the impact of trauma on the body to th...,2000.0,4.27,208.0,1420.0,0,The Body Remembers: The Psychophysiology of Tr...,9780393703276 Relates the impact of trauma on ...
1934,9780393703351,0393703355,Living on the Razor's Edge,Matthew D. Selekman,Psychology,http://books.google.com/books/content?id=hTe40...,"Employing a multifaceted, flexible approach ba...",2002.0,4.00,223.0,4.0,0,Living on the Razor's Edge: Solution-oriented ...,"9780393703351 Employing a multifaceted, flexib..."
2103,9780439286060,0439286069,Freak the Mighty,W. Rodman Philbrick,Juvenile Fiction,http://books.google.com/books/content?id=nkbyg...,"At the beginning of eighth grade, learning dis...",2001.0,4.00,169.0,39447.0,0,Freak the Mighty,9780439286060 At the beginning of eighth grade...
2326,9780449001172,0449001172,Wartime Lies,Louis Begley,Fiction,http://books.google.com/books/content?id=V-aLD...,"A haunting, unforgettable novel about an orpha...",1997.0,3.70,240.0,503.0,0,Wartime Lies,"9780449001172 A haunting, unforgettable novel ..."
2335,9780449149911,0449149919,"Lost Boy, Lost Girl",Peter Straub,Fiction,http://books.google.com/books/content?id=YWrcm...,The bizarre suicide of a woman and the disappe...,2004.0,3.48,368.0,3940.0,0,"Lost Boy, Lost Girl",9780449149911 The bizarre suicide of a woman a...
2343,9780449911419,0449911411,And I Don't Want to Live this Life,Deborah Spungen,Biography & Autobiography,http://books.google.com/books/content?id=4OkkA...,"For most of us, it was just another horrible h...",1996.0,4.09,408.0,4595.0,0,And I Don't Want to Live this Life,"9780449911419 For most of us, it was just anot..."
2351,9780451160317,0451160312,I Never Promised You a Rose Garden,Joanne Greenberg,Mental illness,http://books.google.com/books/content?id=I2R1x...,Chronicles the three-year battle of a mentally...,1989.0,3.86,288.0,23725.0,0,I Never Promised You a Rose Garden,9780451160317 Chronicles the three-year battle...
2457,9780465016907,0465016901,The Drama of the Gifted Child,NaN,Psychology,http://books.google.com/books/content?id=TgtTz...,Why are many of the most successful people pla...,1997.0,4.09,144.0,11373.0,0,The Drama of the Gifted Child: The Search for ...,9780465016907 Why are many of the most success...
2664,9780553212167,0553212168,The Brothers Karamazov,Fyodor Dostoyevsky,Fiction,http://books.google.com/books/content?id=ZI2nc...,The violent lives of three sons are exposed wh...,1970.0,4.32,1072.0,972.0,0,The Brothers Karamazov,9780553212167 The violent lives of three sons ...
2729,9780553560275,0553560271,Shadows,John Saul,Fiction,http://books.google.com/books/content?id=CRxIz...,As one by one the children housed at The Acade...,1993.0,3.92,393.0,10458.0,0,Shadows,9780553560275 As one by one the children house...
3107,9780679761785,0679761780,Blues for Mister Charlie,James Baldwin,Drama,http://books.google.com/books/content?id=vd2JD...,A drama focusing on the murder of a black yout...,1995.0,4.12,144.0,1131.0,0,Blues for Mister Charlie: A Play,9780679761785 A drama focusing on the murder o...
3139,9780684813219,0684813211,Achilles in Vietnam,Jonathan Shay,Psychology,http://books.google.com/books/content?id=6EEnD...,An original and groundbreaking book that exami...,1994.0,4.24,272.0,1057.0,0,Achilles in Vietnam: Combat Trauma and the Und...,9780684813219 An original and groundbreaking b...
3171,9780684867489,0684867486,Yesterday I Cried,Iyanla Vanzant,Self-Help,http://books.google.com/books/content?id=imTTX...,The National Bestseller What is the lesson in ...,2000.0,4.22,304.0,2250.0,0,Yesterday I Cried: Celebrating The Lessons Of ...,9780684867489 The National Bestseller What is ...
3245,9780701179793,0701179791,The Risk of Darkness,Susan Hill,Detective and mystery stories,http://books.google.com/books/content?id=0eouk...,Children have been vanishing - there are no le...,2006.0,3.95,320.0,2913.0,0,The Risk of Darkness: A Simon Serrailler Crime...,9780701179793 Children have been vanishing - t...
3390,9780743454537,0743454537,My Sister's Keeper,Jodi Picoult,Fiction,http://books.google.com/books/content?id=vGZSs...,A popular novel about a girl suing her parents...,2005.0,4.07,423.0,950402.0,0,My Sister's Keeper: A Novel,9780743454537 A popular novel about a girl sui...
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3475,9780747572930,0747572933,A Sound Like Someone Trying Not to Make a Sound,John Irving,Bedtime,http://books.google.com/books/content?id=45_bG...,When a child hears a noise in the night he get...,2004.0,4.01,32.0,664.0,0,A Sound Like Someone Trying Not to Make a Sound,9780747572930 When a child hears a noise in th...
3667,9780765357663,0765357666,Hidden Talents,David Lubar,Juvenile Fiction,http://books.google.com/books/content?id=wgEFP...,When thirteen-year-old Martin Anderson arrives...,2007.0,3.93,240.0,2333.0,0,Hidden Talents,9780765357663 When thirteen-year-old Martin An...
3819,9780802136688,0802136680,This boy's life,Tobias Wolff,Biography & Autobiography,http://books.google.com/books/content?id=JCl2p...,The author chronicles the tumultuous events of...,1999.0,3.98,304.0,22157.0,0,This boy's life,9780802136688 The author chronicles the tumult...
3834,9780802431486,0802431488,The 10 Commandments of Parenting,H. Edwin Young,Religion,http://books.google.com/books/content?id=Q1Hxj...,Drawn from years of counseling and the author'...,2005.0,4.00,224.0,25.0,0,The 10 Commandments of Parenting: The Do's and...,9780802431486 Drawn from years of counseling a...
3925,9780810987906,0810987902,The Boy Who Couldn't Die,William Sleator,Juvenile Fiction,http://books.google.com/books/content?id=72pRX...,"Ken, the only child of rich, indulgent parents...",2005.0,3.68,161.0,1649.0,0,The Boy Who Couldn't Die,"9780810987906 Ken, the only child of rich, ind..."
3954,9780812509670,0812509676,A Fabulous Formless Darkness,David G. Hartwell,Fiction,NaN,Originally published as part of The Dark Desce...,1992.0,4.21,608.0,33.0,0,A Fabulous Formless Darkness,9780812509670 Originally published as part of ...
4294,9780974607894,0974607894,First Love,Ivan Sergeevich Turgenev,Fiction,http://books.google.com/books/content?id=VcNvD...,"This vivid, sensitive tale of adolescent love ...",2004.0,3.79,124.0,5551.0,0,First Love,"9780974607894 This vivid, sensitive tale of ad..."
4325,9781400033416,1400033411,Beloved,Toni Morrison,Fiction,http://books.google.com/books/content?id=Ann5u...,"Sethe, an escaped slave living in post-Civil W...",2004.0,3.81,324.0,263625.0,0,Beloved: A Novel,"9781400033416 Sethe, an escaped slave living i..."
4389,9781400079094,1400079098,Operating Instructions,Anne Lamott,Family & Relationships,http://books.google.com/books/content?id=MiKz2...,A single mother and writer grappling alone wit...,2005.0,4.19,251.0,20993.0,0,Operating Instructions: A Journal Of My Son's ...,9781400079094 A single mother and writer grapp...
4515,9781416939214,1416939210,Z for Zachariah,Robert C. O'Brien,Juvenile Fiction,http://books.google.com/books/content?id=w5Gse...,Believing herself to be the only survivor of a...,2007.0,3.65,250.0,1005.0,0,Z for Zachariah,9781416939214 Believing herself to be the only...
4701,9781573227162,1573227161,Caucasia,Danzy Senna,Fiction,http://books.google.com/books/content?id=QxVzA...,A debut novel explores the complications of ra...,1998.0,4.02,413.0,5991.0,0,Caucasia,9781573227162 A debut novel explores the compl...
4770,9781582433226,1582433224,A Complicated Kindness,Miriam Toews,Fiction,http://books.google.com/books/content?id=Vy6Ct...,"A witty, beleaguered teenager whose family is ...",2005.0,3.65,253.0,17112.0,0,A Complicated Kindness,"9781582433226 A witty, beleaguered teenager wh..."
5071,9781860492914,1860492916,Becoming a Mother,Kate Mosse,Childbirth,http://books.google.com/books/content?id=WKT1G...,Combining medical and historical information w...,1997.0,3.90,392.0,0.0,0,Becoming a Mother,9781860492914 Combining medical and historical...
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,0,"Cry, the Peacock",9788122200850 This book is the story of a youn...